### ISSUE TITLE
[Bug]: App not responding error continuously pops up

### ISSUE THREAD

**Issue by okfrogs** [MelvorIdle/melvoridle.github.io#2594]
### Describe the bug

The android app has been historically very laggy on my Pixel 5a, but in the past few days I've been receiving a "Melvor Idle has stopped responding" error within minutes of launching the app.

This issue seems to happen regardless of what is being trained or what menus I navigate to. The app continues to run despite the error popups, and if I select "wait" I can briefly use the app before the message pops up again. I haven't been able to replicate the issue when nothing is being trained. 

I have tried clearing the app cache, reinstalling the app, and verified my phone and app are up to date. This does not seem to coincide with any recent Android updates. 

### Reproduction Steps

1. Open Melvor Idle
2. Begin training, or open a character with training in progress.
3. Navigate the app (look at bank tab, check another skill, check the shop, etc)
4. Pages typically take 3-5 seconds to accept user input (scrolling, tapping, etc)
5. Melvor Idle has stopped responding error pops up after a few minutes
6. Observe app still functioning (exp and drop notifications are still popping up, combat bars are still moving)
7. Select "wait"
8. Interact with app briefly 
9. Error pops up again. Steps 7-9 can be repeated continuously and the app technically functions as usual.
10. Close app

### Expected behaviour

If the app truly stopped responding I would not expect the game to function normally and accept input between errors, or I would expect the errors to stop popping up constantly. 

### Save Link

https://melvoridle.com/save/cUeqFIpl

### Screenshots

![Screenshot_20220911-085139](https://user-images.githubusercontent.com/107210142/189528478-ea455213-ca0e-4323-8096-8a9d38e3c0f6.png)

https://streamable.com/dhv8rx

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by jonade** [comment]
Exact same problem here, and also with a pixel 5a

**Comment by Incand** [comment]
Same Problem, Pixel 4a (5g)

**Comment by ASRoux** [comment]
Same with Pixel 3a

**Comment by Seb-Looker** [comment]
Same error, Pixel 5.
Could be tied to the update to Android 13?

Duplicate bug here: https://github.com/MelvorIdle/melvoridle.github.io/issues/2609

**Comment by Krackenbracken** [comment]
I fixed this error by disabling all accessibility options in the Android > Settings > Accessibility menu.  In my case, I had an app BlockSite that had accessibility turned on for some reason.

Credit to this thread: https://github.com/MelvorIdle/melvoridle.github.io/issues/2694 

I can finally play this game on phone again! awesome.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
