### ISSUE TITLE
Crashing when entering the shop

### ISSUE THREAD

**Issue by taranpitman** [MelvorIdle/melvoridle.github.io#903]
**Describe the bug**
Hi there, When entering the general shop my game will close after roughly a second, I haven't encountered it on any other page, just the shop page on the steam version. This issue does not occur on my mobile install, or a web installation, tried using new saves as well as my old saves.

**To Reproduce**
honestly nothing to put here.
1: enter the shop on the steam version of melvor idle
2: crash

**Expected behavior**
Crashing is definitely not the intended use of the shop

**Browser**
Steam version, issue does not occur on normal browser or mobile

**Are you using any scripts?**
nope

**Comment by MelvorIdle** [comment]
Should be fixed next major update. Feel free to reopen if not.

**Comment by taranpitman** [comment]
Hi there, I've tested on the latest patch, and the issue is still occurring, still does not occur on normal browsers or mobile, and still occurs on a new save.
